### ISSUE TITLE
Graphics bug after voting

### ISSUE THREAD

**Issue by janmic** [wooga/askmeanything#22]
When I vote on an answer, the index number in the beginning disappears and the results jump to the left. Also, for questions >10 the index number is missing.

http://puu.sh/lGrrN/4fcb8534ea.png

I would consistently either keep the index numbers, or remove them.

[Trello Card](https://trello.com/c/kgW0K4x0/1314-askmeanything-graphics-bug-after-voting)

**Comment by gorenje** [comment]
index up to 10 is desired since only the top 10 are considered, will fix the visual bug if the answer has a ranking otherwise no ranking will be shown.

**Comment by janmic** [comment]
I don't see the value in hiding ranks beyond 10 but whatever, seems like that's the standard reaction to any kind of feedback.
